<?php

/**
 * @file
 * Primary module hooks for Custom Template module.
 */

/**
 * Implements hook_theme().
 */
function custom_template_theme() {
  return [
    'example' => [
      'variables' => ['foo' => NULL],
    ],
  ];
}

/**
 * Prepares variables for example template.
 *
 * Default template: example.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - foo: Foo variable description.
 */
function template_preprocess_example(array &$variables) {
  $variables['foo'] = 'bar';
}
